/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cmakendkdemo_Java2CJni */

#ifndef _Included_com_example_cmakendkdemo_Java2CJni
#define _Included_com_example_cmakendkdemo_Java2CJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cmakendkdemo_Java2CJni
 * Method:    java2c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cmakendkdemo_Java2CJni_java2c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
